[package]
name = "musce_net"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = { workspace = true }
futures-util = { version = "0.3.33", default-features = false, features = ["std", "sink"] }
musce_proto = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.30.0"
tracing = { workspace = true }
