// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One typed canonical value. Entity ids remain strings to preserve all u64 bits.
 */
export type AffordanceValue = { "kind": "entity", id: string, } | { "kind": "text", text: string, } | { "kind": "symbol", domain: string, value: string, };
