// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Perform } from "./Perform";
import type { Query } from "./Query";

/**
 * A message from the web client. The transport parses it and hands the sim a
 * typed [`Input`]. Lifecycle (`Connected`/`Disconnected`) is transport-generated,
 * never sent by a client, so it is absent here.
 */
export type ClientMsg = { "t": "line", line: string, } | { "t": "query" } & Query | { "t": "perform" } & Perform;
