// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node of the containment tree: a projection of the world's containment
 * relation plus the app's name and kinds for the entity, never new state.
 */
export type Entity = { id: string, name: string, 
/**
 * App kind tags (e.g. "container", "item", "exit", "locked").
 */
kinds: Array<string>, 
/**
 * Ids directly contained by this entity.
 */
contents: Array<string>, 
/**
 * App-projected passive detail as ordered `(label, value)` pairs (e.g. a
 * `("description", ...)`). Opaque to the wire: the app decides what an actor
 * perceives by presence and the client just paints the pairs. This is the
 * same prose a narrated `examine` reveals, delivered silently as part of the
 * read, so the pointing client renders a focused entity without a round-trip.
 */
details: Array<[string, string]>, };
