// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AffordanceValue } from "./AffordanceValue";

/**
 * App-selected presentation candidates for one missing input.
 */
export type InputCandidates = { parameter: string, values: Array<AffordanceValue>, };
