// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * How an affordance stands for the clicked entity: a live control, a greyed one
 * carrying the reason, or one that opens a sub-pick for a still-unbound role.
 */
export type OfferStatus = { "kind": "available" } | { "kind": "vetoed", reason: string, } | { "kind": "needsRole", role: Role, };
