// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferStatus } from "./OfferStatus";

/**
 * One enumerated act on a clicked entity: the affordance name and its status. The
 * wire form of `musce_ref::offers::Offer`.
 */
export type Offer = { name: string, status: OfferStatus, };
