// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current classification of an app-exposed partial grounding.
 */
export type OfferStatus = { "kind": "available" } | { "kind": "vetoed", reason: string, } | { "kind": "needs", parameters: Array<string>, };
