// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputCandidates } from "./InputCandidates";
import type { OfferStatus } from "./OfferStatus";
import type { ParameterBinding } from "./ParameterBinding";
import type { ParameterDecl } from "./ParameterDecl";

/**
 * One app-exposed partial canonical grounding and its engine classification.
 */
export type Offer = { affordance: string, display_name: string, parameters: Array<ParameterDecl>, bindings: Array<ParameterBinding>, candidates: Array<InputCandidates>, status: OfferStatus, };
