// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical parameter mode. The client may bind inputs only; results are shown
 * in signatures and returned by the server.
 */
export type ParameterMode = "input" | "result";
