// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterMode } from "./ParameterMode";
import type { ParameterSort } from "./ParameterSort";

/**
 * One app-defined parameter declaration carried in an offer.
 */
export type ParameterDecl = { id: string, label: string, sort: ParameterSort, mode: ParameterMode, };
