// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AffordanceValue } from "./AffordanceValue";

/**
 * A value bound to one stable app-defined parameter id.
 */
export type ParameterBinding = { parameter: string, value: AffordanceValue, };
