// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical value sort in a wire-safe representation.
 */
export type ParameterSort = { "kind": "entity" } | { "kind": "text" } | { "kind": "symbol", domain: string, };
