// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A grounded act request: the client already holds the entity id, so this carries
 * the affordance name and its bound entities directly, with no noun to resolve.
 * `focus` is the clicked entity; `with` is the optional second entity a role
 * sub-pick supplied (the object to `put`, once the container is the focus). Which
 * role `focus` fills is game policy, so the game maps `focus`/`with` onto the
 * affordance's roles.
 */
export type Perform = { name: string, focus: string, with: string | null, };
