// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterBinding } from "./ParameterBinding";

/**
 * Successful typed results from one committed affordance.
 */
export type Performed = { affordance: string, results: Array<ParameterBinding>, };
