// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterBinding } from "./ParameterBinding";

/**
 * A complete canonical act request. Bindings name app-defined input parameters;
 * there are no engine-defined roles or fixed arity. Actor identity comes from the
 * authenticated session and results are server-produced only.
 */
export type Perform = { affordance: string, inputs: Array<ParameterBinding>, };
