// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read the client asks of the world, answered by a [`ServerMsg`] reply; it never
 * mutates. Acting on an entity (`perform`) is a command, not a query, and lands in
 * a later slice.
 */
export type Query = { "q": "snapshot" } | { "q": "offers", clicked: string, };
