// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The frame role a still-unbound pick fills.
 */
export type Role = "object" | "target";
