// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";
import type { Offer } from "./Offer";
import type { Performed } from "./Performed";
import type { SnapshotData } from "./SnapshotData";

/**
 * A message to the web client: a streamed event or a query reply, tagged so the
 * client can route it. The transport serializes this; the sim produces the
 * in-process forms (`Delivery` for events, this enum for replies).
 */
export type ServerMsg = { "t": "event", kind: EventKind, text: string, } | { "t": "snapshot" } & SnapshotData | { "t": "offers", clicked: string, offers: Array<Offer>, } | { "t": "performed" } & Performed;
