// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";

/**
 * The snapshot reply payload: the tree root (the actor's room), the actor, and
 * every perceivable entity. `entities[actor].contents` is the actor's inventory,
 * so it needs no separate query.
 */
export type SnapshotData = { root: string, actor: string, entities: Array<Entity>, };
